import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Linoy Katz",
      email: "katzlinoy27@gmail.com",
      phone: "050-1234567",
      password: bcrypt.hashSync("111"),
      isAdmin: true,
    },
    {
      name: "Arik Alexandrov",
      phone: "050 9876543",
      email: "arik@gmail.com",
      password: bcrypt.hashSync("222"),
      isAdmin: false,
    },
  ],

  products: [
    {
      title: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Men-shirts",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686643700/Ella2023/zr900qfo44aeemyvr9ww.jpg",
      price: 39.99,
      isTop4: true,
      stock: 7,
      brand: "Nike",
      rating: 4.5,
      numOfReviews: 10,
      desc: "High quality shirt",
    },
    {
      title: "Adidas Fit pants",
      slug: "adidas-fit-pants",
      category: "Men-pants",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686643769/Ella2023/ur5wnssak1tzlgnkxksi.jpg",
      price: 59.99,
      isTop4: true,
      stock: 2,
      brand: "Adidas",
      rating: 5,
      numOfReviews: 33,
      desc: "Best pants in the world",
    },
    {
      title: "Nike Slim pants",
      slug: "nike-slim-pants",
      category: "Men-pants",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686643835/Ella2023/ekgj8rcewu91jovvqctp.jpg",
      price: 80.0,
      isTop4: true,
      stock: 8,
      brand: "Nike",
      rating: 4,
      numOfReviews: 11,
      desc: "High quality pants",
    },
    {
      title: "Adidas Slim shirt",
      slug: "adidas-slim-shirt",
      category: "Men-shirts",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686643862/Ella2023/dsviwcsjzyuvx1yzqhyn.jpg",
      price: 39.9,
      isTop4: true,
      stock: 0,
      brand: "Adidas",
      rating: 1.5,
      numOfReviews: 0,
      desc: "great shirt",
    },
    {
      title: "Blue Women shirt",
      slug: "blue-women-shirt",
      category: "Women-shirts",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686660977/Ella2023/w6wutcylhld8mmay318u.png",
      price: 49.99,
      isTop4: false,
      stock: 7,
      brand: "Sheim-design",
      rating: 4.5,
      numOfReviews: 14,
      desc: "Great classic shirt",
    },
    {
      title: "Green Women shirt",
      slug: "geen-women-shirt",
      category: "Women-shirts",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686823522/Ella2023/eyoookqcvqxqivtzixwg.png",
      price: 39.9,
      isTop4: false,
      stock: 7,
      brand: "Sheim-design",
      rating: 4,
      numOfReviews: 10,
      desc: "Great green shirt",
    },
    {
      title: "Sheim White shirt",
      slug: "sheim-slim-white-shirt",
      category: "Women-shirts",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686823784/Ella2023/f4qyilla0mi1wgenq4hv.png",
      price: 29.99,
      isTop4: false,
      stock: 6,
      brand: "Sheim-design",
      rating: 3,
      numOfReviews: 30,
      desc: "High quality shirt",
    },
    {
      title: "Nike Pink Vest",
      slug: "nike-pink-vest",
      category: "Women-shirts",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686824953/Ella2023/bzerghajep9d5q0nhrxa.png",
      price: 49.9,
      isTop4: false,
      stock: 8,
      brand: "Nike",
      rating: 5,
      numOfReviews: 20,
      desc: "High quality pink vest",
    },
    {
      title: "Adidas Slim shirt2",
      slug: "adidas-slim-shir2t",
      category: "Women-shirts",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1686825273/Ella2023/raygxyh0mzlqbuchnvvp.png",
      price: 60,
      isTop4: false,
      stock: 0,
      brand: "Adidas",
      rating: 5,
      numOfReviews: 33,
      desc: "High quality white shirt",
    },
    {
      title: "Nike black jeans",
      slug: "nike-black-jeans",
      category: "Women-pants",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687166954/Ella2023/quzvnpfpheoct93i35ay.png",
      price: 59.9,
      isTop4: false,
      stock: 10,
      brand: "Nike",
      rating: 5,
      numOfReviews: 7,
      desc: "strech pants",
    },
    {
      title: "Mid waist jeans",
      slug: "mid-waist-jeans",
      category: "Women-pants",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687167514/Ella2023/cgsaxmltiuts0zyt09sk.png",
      price: 59.9,
      isTop4: false,
      stock: 10,
      brand: "Nike",
      rating: 5,
      numOfReviews: 7,
      desc: "strech pants",
    },
    {
      title: "Adidas gray sweatpants",
      slug: "Adidas-gray-sweatpants",
      category: "Women-pants",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687168355/Ella2023/so01yaatcwoswlwrggmf.png",
      price: 69.99,
      isTop4: false,
      stock: 2,
      brand: "Adidas",
      rating: 5,
      numOfReviews: 47,
      desc: "Sweatpants",
    },
    {
      title: "mustard pants",
      slug: "mustard-pants",
      category: "Women-pants",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687168474/Ella2023/sanb47gzvoo6w4tjhp50.png",
      price: 59.9,
      isTop4: false,
      stock: 10,
      brand: "Sheim-design",
      rating: 3.5,
      numOfReviews: 11,
      desc: "Casual pants",
    },
    {
      title: "brown pants",
      slug: "brown-pants",
      category: "Women-pants",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687168596/Ella2023/jkoqkt5rndjcy73rbdwf.png",
      price: 59.9,
      isTop4: false,
      stock: 8,
      brand: "Sheim-design",
      rating: 3,
      numOfReviews: 7,
      desc: "brown pants",
    },
    {
      title: "Black night dress",
      slug: "black-night-dress",
      category: "Women-lingerie",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687168842/Ella2023/r1jsbhqh8ty2mxj4jgy2.png",
      price: 129.99,
      isTop4: false,
      stock: 10,
      brand: "Sheim-design",
      rating: 5,
      numOfReviews: 32,
      desc: "Black comfortable night dress",
    },
    {
      title: "Black lace set",
      slug: "Black-lace-set",
      category: "Women-lingerie",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687168949/Ella2023/u1livlnya5gm0xrpwx4x.png",
      price: 99.99,
      isTop4: false,
      stock: 6,
      brand: "Sheim-design",
      rating: 5,
      numOfReviews: 45,
      desc: "Black lace set",
    },
    {
      title: "Sexy red set",
      slug: "Sexy-red-set",
      category: "Women-lingerie",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687169041/Ella2023/af8z0ctjominzfn4fude.png",
      price: 129.99,
      isTop4: false,
      stock: 10,
      brand: "Sheim-design",
      rating: 4.5,
      numOfReviews: 23,
      desc: "Sexy red lace set",
    },
    {
      title: "Purple pushup set",
      slug: "Purple-pushup-set",
      category: "Women-lingerie",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687169144/Ella2023/scixng3zwsqnoh6simij.png",
      price: 116.99,
      isTop4: false,
      stock: 6,
      brand: "Nike",
      rating: 5,
      numOfReviews: 17,
      desc: "Purple pushup set",
    },
    {
      title: "2 kids pjs pack",
      slug: "2-kids-pjs-pack",
      category: "Kids",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687169271/Ella2023/ofckezjxenpevkrwtjpt.png",
      price: 133.99,
      isTop4: false,
      stock: 10,
      brand: "Sheim-design",
      rating: 4.5,
      numOfReviews: 21,
      desc: "2 kids pjs pack",
    },
    {
      title: "Pink kids dress",
      slug: "Pink-kids-dress",
      category: "Kids",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687169489/Ella2023/vuoqb4qvxehpyah7a0gw.png",
      price: 78.99,
      isTop4: false,
      stock: 4,
      brand: "Sheim-design",
      rating: 5,
      numOfReviews: 56,
      desc: "Good quallity pink kids dress",
    },
    {
      title: "2 Basic black shirts",
      slug: "2-basic-black-shirts",
      category: "Kids",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687169649/Ella2023/binpcy2vsrktksqvoc5g.png",
      price: 133.99,
      isTop4: false,
      stock: 10,
      brand: "Sheim-design",
      rating: 4.5,
      numOfReviews: 21,
      desc: "good fabric black shirts",
    },
    {
      title: "2 Basic white shirts",
      slug: "2-basic-white-shirts",
      category: "Kids",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687169755/Ella2023/dstvs4ayzmzwhq5djgoz.png",
      price: 133.99,
      isTop4: false,
      stock: 5,
      brand: "Sheim-design",
      rating: 5,
      numOfReviews: 34,
      desc: "good fabric white shirts",
    },
    {
      title: "buttoned kids shirt",
      slug: "buttoned-kids-shirt",
      category: "Kids",
      img1: "https://res.cloudinary.com/arikxl/image/upload/v1687169876/Ella2023/clipd4r7yh8ddjfo662x.png",
      price: 60.0,
      isTop4: false,
      stock: 9,
      brand: "Sheim-design",
      rating: 3,
      numOfReviews: 11,
      desc: "Cute buttoned shirt",
    },
  ],
};

export default data;
